# This file tells GitHub to automatically deploy to Firebase 
# whenever you push a change to the main branch.

name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_SUPPORT_MY_LOCAL_COMMUNITY }}
          channelId: live
          projectId: support-my-local-community
